# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3298119dc873674881d7944360d2b2cad8661cdcdedc6e8b04f6c976439fb1394f83642194a40b8489fbf559b0513daf60e3f023fc1dbdec5f2d7308bd18761f

test:
  secret_key_base: 52f4abe6c44821f902ea6402f0558c7bd0c735e8396ef4c19de5c5392622e2a3e66c713918c92c9d3dd8ebe777567a9fac4177a980dc3293a7180be7935d9d36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
